import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';

const products = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/products' }),
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    category: z.enum(['children', 'medical', 'critical-illness', 'savings', 'pension', 'overseas-assets']),
    summary: z.string(),
    audience: z.array(z.string()).default([]),
    productLines: z.array(z.enum(['health', 'accident', 'critical-illness', 'retirement', 'wealth', 'legacy'])).min(1),
    audiences: z.array(z.enum(['adult', 'child'])).min(1),
    officialUrl: z.string().url().optional(),
    layoutVariant: z.enum(['medical', 'critical', 'wealth']).default('medical'),
    medicalCosts: z.array(z.object({ responsibility:z.string(), limit:z.string(), deductible:z.string(), ratio:z.string(), note:z.string() })).default([]),
    premiumDisplayMode: z.enum(['structured', 'image', 'both']).default('structured'),
    premiumImage: z.string().optional(),
    premiumImageMobile: z.string().optional(),
    premiumImageAlt: z.string().optional(),
    premiumCards: z.array(z.object({
      ageRange:z.string(), tone:z.enum(['blue','salmon']).default('blue'),
      primaryTag:z.string(), primaryName:z.string(), primaryPrice:z.string(),
      riderTag:z.string(), riderName:z.string(), riderPrice:z.string(), total:z.string(),
    })).default([]),
    coveragePlans: z.array(z.object({
      title:z.string(), tone:z.enum(['blue','salmon']).default('blue'),
      responsibilities:z.array(z.object({
        number:z.string(), title:z.string(), text:z.string(), emphasis:z.string().optional(),
        rates:z.array(z.object({ label:z.string(), note:z.string().optional(), rate:z.string(), tone:z.enum(['green','olive','purple']).optional() })).default([]),
      })).default([]),
      extras:z.array(z.object({ title:z.string(), text:z.string() })).default([]),
    })).default([]),
    criticalPremiums: z.array(z.object({ tier:z.string(), coverage:z.string(), premium:z.string(), riders:z.string(), note:z.string() })).default([]),
    wealthCashflows: z.array(z.object({ age:z.string(), premiumCoverage:z.string(), payoutAge:z.string(), benefit:z.string(), note:z.string() })).default([]),
    heroImage: z.string().optional(),
    heroImagePosition: z.string().default('center'),
    featured: z.boolean().default(false),
    status: z.enum(['draft', 'reviewed', 'published']).default('draft'),
    sortOrder: z.number().int().default(100),
    updatedAt: z.coerce.date(),
    region: z.string().default('中国大陆'),
    seoTitle: z.string(),
    seoDescription: z.string(),
    painPoints: z.array(z.object({ title: z.string(), text: z.string() })).default([]),
    highlights: z.array(z.object({ title: z.string(), text: z.string() })).default([]),
    coverage: z.array(z.object({ title: z.string(), value: z.string(), text: z.string() })).default([]),
    cases: z.array(z.object({
      title:z.string(), scenario:z.string(), result:z.string(), image:z.string().optional(),
      settlementHeading:z.string().optional(),
      settlementExpenses:z.array(z.object({ label:z.string(), value:z.string(), accent:z.boolean().default(false) })).default([]),
      withoutInsuranceTitle:z.string().optional(), withoutInsuranceLines:z.array(z.string()).default([]), withoutInsuranceTotal:z.string().optional(),
      withInsuranceTitle:z.string().optional(), withInsuranceLines:z.array(z.string()).default([]), withInsuranceTotal:z.string().optional(),
      settlementHighlight:z.string().optional(),
    })).default([]),
    comparison: z.array(z.object({ label: z.string(), product: z.string(), market: z.string() })).default([]),
    faq: z.array(z.object({ question: z.string(), answer: z.string() })).default([]),
    claimCases: z.array(z.object({ title:z.string(), background:z.string(), customer:z.string(), result:z.string(), documentImage:z.string().optional() })).default([]),
    knowledgeTitle: z.string().optional(),
    knowledgeIntro: z.string().optional(),
    knowledgeItems: z.array(z.object({ label:z.string(), title:z.string(), text:z.string() })).default([]),
    knowledgeNote: z.string().optional(),
    sourceText: z.string().default('产品资料及保险合同责任摘要'),
    comparisonBasis: z.string().default('仅比较责任结构，不构成对市场全部产品的穷尽比较。'),
    disclaimer: z.string().default('本页面仅用于保险知识普及，具体责任与内容以正式保险合同及最新产品资料为准。'),
    ctaTitle: z.string().default('预约一对一咨询'),
    ctaText: z.string().default('获得适合家庭实际情况的保障梳理。'),
    qrImage: z.string().optional(),
  }),
});

const knowledge = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/knowledge' }),
  schema: z.object({
    title:z.string(),
    slug:z.string(),
    category:z.enum(['medical-policy','insurance-selection','claims','health','family-planning']),
    summary:z.string(),
    coverImage:z.string().optional(),
    featured:z.boolean().default(false),
    status:z.enum(['draft','reviewed','published']).default('draft'),
    updatedAt:z.coerce.date(),
    seoTitle:z.string(),
    seoDescription:z.string(),
    sourceText:z.string().optional(),
    disclaimer:z.string().default('本文仅用于保险及健康知识交流，不构成诊断、治疗、投保建议或销售承诺。'),
    authorLabel:z.string().default('未来可乐团队'),
  }),
});

export const collections = { products, knowledge };
